### ISSUE TITLE
Cambios solicitados

### ISSUE THREAD

**Issue by CarlosRubioTNM** [kevlozruiz/PracticasBISON#1]
Buen trabajo, jóvenes. 

Ahora, para terminar con la práctica les voy a pedir que realicen los siguientes cambios:

1. En la página "Acerca de Mí" hay un par de errores de ortografía (por ejemplo: "comprenderas"). Revisen y corrijan esa parte.
2. Añadir en la página "Acerca de Mí" la misión y visión (inventadas) de la empresa.
3. Colocar un pié de página en todas donde se inventen un número de contacto y el año del Copyright de la empresa (2022).

Cuando terminen, avísenme en este hilo para revisar los cambios. Saludos.

**Comment by kevlozruiz** [comment]
@CarlosRubioTNM  Profe, ya realizamos los cambios solicitados. Quedamos atentos a sus comentarios, saludos!

**Comment by CarlosRubioTNM** [comment]
Excelente, jóvenes. Cierro el issue. 👍
